### ISSUE TITLE
suggestion: Backup on start / exit?

### ISSUE THREAD

**Issue by Kroc** [spikegrobstein/mcwrapper#10]
Perhaps the option to backup the world before the server starts, and then when the server quits. Not sure how you would handle versioning here, perhaps use "worldname-start-timestamp" and "worldname-stop-timestamp".

**Comment by spikegrobstein** [comment]
yeah, this one I'll postpone for down the line a bit. Not sure what the best way to work out the details is.

**Comment by spikegrobstein** [comment]
implemented a BACKUP_ON_EXIT conf option. will NOT back anything up if backups are disabled (BACKUPS_TO_KEEP=0).
