### ISSUE TITLE
Include a start script

### ISSUE THREAD

**Issue by Kroc** [spikegrobstein/mcwrapper#2]
mcwrapper cannot be used until you first either write a script yourself to start it, or execute it from the command line.

For user friendliness, a start script should be included for people who don’t know how to script and just want to be able to start and stop the server (the ultimate goal being that this start script will also start a regular backup timer).

Initially, this script doesn't need to be any more complex than `./mcwrapper`; it's purely there for the kinds of people who prefer to double-click on things.

**Comment by spikegrobstein** [comment]
what do you think of a series of commands in a directory such as:
- mc_start
- mc_stop
- mc_restart
- (etc)

all doubleclickable and all simply call mcwrapper with the appropriate command?

**Comment by Kroc** [comment]
Agreed. Makes it easy for non command line users to do everything they need.

**Comment by spikegrobstein** [comment]
added start, stop, restart, and backup scripts to a scripts folder... need to write up documentation, but closing the ticket now.

this all lives in the unstable/1.4 branch (right now).
