### ISSUE TITLE
Determine MCWRAPPER_DIR with absolute path

### ISSUE THREAD

**Issue by daschu117** [spikegrobstein/mcwrapper#25]
If you change this:
MCWRAPPER_DIR=`dirname "$MCWRAPPER"`

to this:
MCWRAPPER_DIR=$(readlink -f ${0%/*})

the script is better able to determine where mcwrapper exists by having an absolute path instead of a relative one based off the pwd.

This was causing problems for me when calling mcwrapper from my home directory. If I called it by "minecraft/mcwrapper status" it was unable to determine the status, but "./minecraft/mcwrapper status" worked just fine.

**Comment by spikegrobstein** [comment]
ack.

What OS/distro are you on?

One issue I ran into using `readlink -f` is that the `readlink` provided by OSX does not have a -f equivalent.

I'd tested the hell out of this on both Ubuntu and OSX and I thought I had it nailed down. I'll screw with it some more.

**Comment by daschu117** [comment]
I'm running it on Archlinux. It's a shame that readlink isn't as cross platform as it should be. Considering that its a minor inconvenience and running it via a full absolute path via cron works great, I suppose that it's fine the way it is.

But thanks for checking and the quick reply! :-)

**Comment by spikegrobstein** [comment]
I finally got this fixed. Sorry for the delay, I've been super busy with other projects. It's in the current release/1.4 branch as well as unstable/1.5.

The fix came from another user who had me use a pushd/popd trick. It's pretty slick.
