### ISSUE TITLE
'mcwrapper status' should return different values based on status

### ISSUE THREAD

**Issue by daschu117** [spikegrobstein/mcwrapper#26]
It would be useful if `mcwrapper status` returned differently depending on if the server is running or not. This would prevent having to redirect stderr to stdout, then grep for "Server is running."

Thanks! :-D

**Comment by spikegrobstein** [comment]
Hey again! That's already in the unstable/1.5 branch. It's got a pretty complete list of exit codes depending on what the outcome was.

I'm aiming to get that completed and released by the end of this week. Been kinda busy the last couple weeks and haven't had time to work on this.
