### ISSUE TITLE
mcwrapperc is a bad name for a config file.

### ISSUE THREAD

**Issue by Kroc** [spikegrobstein/mcwrapper#3]
You unzip the download—you haven't bothered with the README, nobody does—and you stare at the plethora of files in front of you. Where do you start? There’s mcwrapper, and mcwrapperc. Is one a C version of the other??

Please name the config file something obvious so people know what to do when they look at the directory of files. :)

**Comment by spikegrobstein** [comment]
I was on the fence with this when I named it. I felt that it wasn't a config because it's actually sourcing the file as bash to read the configuration. Perhaps renaming it to mcwrapper.conf would be better in the longrun, though.

I'll add this to my todo list.
