### ISSUE TITLE
Include a clean exit command

### ISSUE THREAD

**Issue by Kroc** [spikegrobstein/mcwrapper#5]
Mcwrapper should include a clean exit command, e.g. `mcwrapper exit` that will check if the Minecraft server is running and if so, save-all, stop the server, and then end mcwrapper. This could also be used to do some clean up, like removing the PID file.

**Comment by spikegrobstein** [comment]
There actually is `mcwrapper stop` which cleanly stops the server and removes the PID. This `stop` action is part of the minecraft server command list and does an implicit save-all before shutting down and exiting.

I should probably add `stop` to the docs even though it's the server that's handling it as opposed to mcwrapper itself (although it does do some special things before passing that command to the server).

I guess I might also want to remove the FIFO, too. hmm.

**Comment by Kroc** [comment]
Didn't know that, agreed.
