### ISSUE TITLE
Provide a backup timer

### ISSUE THREAD

**Issue by Kroc** [spikegrobstein/mcwrapper#6]
Not sure how you would exactly do this, I’m not well versed in the art of bash-fu. Basically, please include a config option to automatically back up every X minutes whilst the server is running. Having this would make mcwrapper perfect out of the box to start using.

**Comment by spikegrobstein** [comment]
I don't agree with this one. I'm willing to create a launchd config (for OSX users) and a line in the documentation to paste into the crontab (for linux users), but I don't want to re-invent cron just for less technical users.
