### ISSUE TITLE
mcbackup: read WORLD_DIR from server.properties

### ISSUE THREAD

**Issue by Kroc** [spikegrobstein/mcwrapper#7]
mcbackup assumes that the server’s world folder is called "world". It should instead read the world name (`level-name`) from Minecraft Server’s config file, since the name may be different (in my case, it is),

(mcbackup should also check that this folder exists)

**Comment by spikegrobstein** [comment]
I added a new function that can read any server.properties property and return it. It's now used internally to find the level-name when doing backups. Also, I added a new external action called 'prop' which can be used to read properties from an external script.

eg:

./mcwrapper prop level-name
