### ISSUE TITLE
mcbackup: use ZIPs instead of copying folders

### ISSUE THREAD

**Issue by Kroc** [spikegrobstein/mcwrapper#8]
Idea: (you may disagree, I wouldn’t mind) mcbackup should zip the world folder to back it up, rather than copying the whole folder. Using ZIPs takes up less space, is tidier quicker to transfer to other locations (if moving a backup file between computers).

When backing up, mcbackup should zip the world folder into a zip file that has the datetime appended to the name. The zip itself should be made of the folder, not just its contents, so that when unzipped it results in a folder with the _original world name_ (sans time-stamp). This makes it quicker to restore from backup.

**Comment by spikegrobstein** [comment]
I agree on the first half. I'm planning on supporting tgz, zip and bz2, but I don't know how I feel about unzipping back to 'world'. I wouldn't want a user to inadvertently unzip and overwrite anything.

I would like to create a method of restoring from backup, though. Where you can tell it to restore a certain backup file and it'll rename the current world and restore the backup to keep that easy.

I've got to ponder that detail a little bit. I'll make it both ways and see which I like better...

**Comment by Kroc** [comment]
No, I’m not asking for mcwrapper/backup to actually unzip the file for you, no. Just that the zip is created in such a way that the original folder name is preserved :)

I think it’s not necessary for mcwrapper to provide restore, the file system is right there already. If the user knew how to install mcwrapper, they already know how to unzip the backup and put the world folder back where it came from.

**Comment by spikegrobstein** [comment]
I've got this mostly complete. just gotta do some QA and make sure that it's not buggy or anything.

right now the backups are stand-alone archives. The thing is that I'm not only saving the world data, but also the current configuration of the server (properties, whitelists, banlists, etc). I'll have to figure out if there is a simple enough way to do the trick with the world archive and everything else.

I think that'll have to be a feature in the future. Gonna close this ticket.
